/**
 * Copyright 2011 DALLAS Alexandros (dallas.alexandros@gmail.com)
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

package gr.gsis.wsnp;

import java.math.BigDecimal;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "RgWsBasStoixN", targetNamespace = "http://gr/gsis/rgwsbasstoixn/RgWsBasStoixN.wsdl")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface RgWsBasStoixN {


    /**
     * 
     * @param pAfm
     * @param pBasStoixNRecOut
     * @param pCallSeqIdOut
     * @param pErrorRecOut
     */
    @WebMethod(action = "http://gr/gsis/rgwsbasstoixn/RgWsBasStoixN.wsdl/rgWsBasStoixN")
    public void rgWsBasStoixN(
        @WebParam(name = "pAfm", partName = "pAfm")
        String pAfm,
        @WebParam(name = "pBasStoixNRec_out", mode = WebParam.Mode.INOUT, partName = "pBasStoixNRec_out")
        Holder<RgWsBasStoixNRtUser> pBasStoixNRecOut,
        @WebParam(name = "pCallSeqId_out", mode = WebParam.Mode.INOUT, partName = "pCallSeqId_out")
        Holder<BigDecimal> pCallSeqIdOut,
        @WebParam(name = "pErrorRec_out", mode = WebParam.Mode.INOUT, partName = "pErrorRec_out")
        Holder<GenWsErrorRtUser> pErrorRecOut);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://gr/gsis/rgwsbasstoixn/RgWsBasStoixN.wsdl/rgWsBasStoixNVersionInfo")
    @WebResult(name = "result", partName = "result")
    public String rgWsBasStoixNVersionInfo();

}
